import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'
import fs from 'node:fs'

// Injects the current legal texts (src/legal-snapshot.json, generated by scripts/render-legal.mjs)
// into the home page's pop-ups.
const legalInject = () => ({
  name: 'legal-inject',
  transformIndexHtml: {
    order: 'pre',
    handler(html) {
      if (!html.includes('__LEGAL_JSON__')) return html;
      const json = fs.readFileSync(resolve(__dirname, 'src/legal-snapshot.json'), 'utf8');
      return html.replace('__LEGAL_JSON__', () => JSON.stringify(JSON.parse(json)).replace(/</g, '\\u003c'));
    }
  }
});

// Custom Vite middleware to rewrite local /go/:providerId queries to /go/index.html during dev
const goRouteDevMiddleware = () => ({
  name: 'go-route-dev-middleware',
  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      // Catch any URL starting with /go/ (excluding file extensions or paths with dots like JS/CSS assets)
      if (req.url && req.url.startsWith('/go/') && !req.url.includes('.')) {
        req.url = '/go/index.html';
      }
      next();
    });
  }
});

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), goRouteDevMiddleware(), legalInject()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        go: resolve(__dirname, 'go/index.html')
      }
    }
  }
})
