import React from 'react';

function TermsOfService({ onBack }) {
  return (
    <div className="legal-container">
      <button className="back-btn" onClick={onBack} aria-label="Back to Home">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
          <line x1="19" y1="12" x2="5" y2="12"></line>
          <polyline points="12 19 5 12 12 5"></polyline>
        </svg>
        <span>Back to Home</span>
      </button>

      <header className="legal-header">
        <h1 className="legal-title">Terms of Service</h1>
        <div className="legal-meta">Last Updated: August 2026</div>
      </header>

      <section className="legal-section">
        <h2>1. Acceptance & The Service</h2>
        <p className="legal-text">
          By accessing, browsing, or using the Chiller Travel website and our AI-powered travel planning companion, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. Chiller Travel provides an artificial intelligence planning utility designed to suggest itineraries, routes, activities, and accommodation options. All outputs and recommendations generated by our bot are provided for general informational and travel planning purposes only, and should not be relied upon as absolute or final.
        </p>
      </section>

      <section className="legal-section">
        <h2>2. Affiliate Disclosure</h2>
        <p className="legal-text">
          Chiller Travel participates in affiliate marketing programs. This means that we embed specialized referral links to third-party travel, lodging, flight, and tour providers. When users click on these links and complete a purchase or booking, Chiller Travel receives a referral commission from the respective provider. These transactions occur at absolutely no additional cost to the user, and our affiliate relationships do not influence the price you pay.
        </p>
      </section>

      <section className="legal-section">
        <h2>3. Dynamic Pricing & Availability</h2>
        <p className="legal-text">
          All rates, fees, timetables, and booking availability details displayed or suggested by the AI travel bot fluctuate in real-time based on supplier demand, seasonal changes, and inventory updates. Chiller Travel does not guarantee pricing or room/seat availability. Prices and bookings are only locked and legally binding once they are fully paid, confirmed, and receipted on the external third-party provider's official platform.
        </p>
      </section>

      <section className="legal-section">
        <h2>4. Medical, Safety & Backpacker Insurance</h2>
        <p className="legal-text">
          The travel and itinerary recommendations provided by our AI assistant are for general guidance and backpacking inspiration only. They do not constitute professional, legal, medical, or official safety advice. Backpacker travel and adventure activities involve inherent dangers. Users are solely and exclusively responsible for obtaining comprehensive travel insurance that includes coverage for high-risk activities, extreme sports, and high-altitude trekking, as well as obtaining professional medical advice, required vaccines, and assessing the safety, weather, and physical conditions at their destinations. Chiller Travel assumes no liability whatsoever for injuries, illnesses, accidents, property damage, or financial losses incurred during travel.
        </p>
      </section>

      <section className="legal-section">
        <h2>5. Visas, Passports & Border Crossings</h2>
        <p className="legal-text">
          Crossing international borders, accessing remote regions, or entering foreign countries requires strict legal documentation. You are solely and exclusively responsible for verifying your passport validity, acquiring required visas, permits, or tourist cards, and checking land, sea, or air border crossing regulations for any route suggested by our AI bot. Chiller Travel is not responsible for entry denials, detentions, or travel cancellations resulting from visa or documentation issues.
        </p>
      </section>

      <section className="legal-section">
        <h2>6. Cancellations & Consumer Law</h2>
        <p className="legal-text">
          Chiller Travel functions strictly as an affiliate referral platform. We are not a travel agency, tour operator, booking merchant, or merchant of record. We do not collect payments, issue tickets, or handle reservation modifications. Consequently, any cancellations, refund requests, scheduling modifications, or customer service issues are subject strictly to the terms, conditions, cancellation policies, and local consumer protection laws (including the Israeli Consumer Protection Law, where legally applicable) of the end supplier or third-party service provider. Any legal claims, disputes, or complaints must be filed directly against the end supplier, and not against Chiller Travel.
        </p>
      </section>

      <section className="legal-section">
        <h2>7. Intellectual Property & User Conduct</h2>
        <p className="legal-text">
          All text, graphics, user interface designs, logos, software, and AI-generated outputs (including custom travel itineraries) displayed on Chiller Travel are protected by intellectual property laws. Users are strictly prohibited from scraping, copying, replicating, reverse-engineering, commercializing, reselling, or republishing the AI-generated itineraries, site data, database contents, or bot outputs for any commercial or public purpose without our prior written consent.
        </p>
      </section>

      <section className="legal-section">
        <h2>8. Contact Info</h2>
        <div className="legal-highlight-box">
          <p>
            For any inquiries, contact us at <a href="mailto:chillerbot1405@gmail.com" className="legal-link">chillerbot1405@gmail.com</a>. Please include your full name in your message.
          </p>
        </div>
      </section>

      <hr className="legal-divider" />

      <div className="rtl-container" dir="rtl">
        <header className="legal-header" style={{ borderBottomColor: 'rgba(255, 255, 255, 0.08)' }}>
          <h1 className="legal-title" style={{ fontSize: '2.4rem' }}>תנאי שימוש</h1>
          <div className="legal-meta" style={{ textAlign: 'right' }}>עודכן לאחרונה: אוגוסט 2026</div>
        </header>

        <section className="legal-section">
          <h2 style={{ fontSize: '1.4rem', color: '#38bdf8' }}>1. קבלת התנאים והשירות</h2>
          <p className="legal-text">
            בעצם הגישה, הגלישה או השימוש באתר Chiller Travel ובכלי תכנון הנסיעות מבוסס הבינה המלאכותית (AI) שלנו, אתם מאשרים כי קראתם, הבנתם ואתם מסכימים להיות כפופים לתנאי שימוש אלה. Chiller Travel מספקת כלי תכנון המבוסס על בינה מלאכותית שנועד להציע מסלולי טיול, דרכי הגעה, פעילויות ואפשרויות לינה. כל הפלטים וההמלצות המופקים על ידי הבוט שלנו מסופקים לצורכי תכנון כללי ומידע בלבד, ואין להסתמך עליהם כנתונים מוחלטים או סופיים.
          </p>
        </section>

        <section className="legal-section">
          <h2 style={{ fontSize: '1.4rem', color: '#38bdf8' }}>2. גילוי נאות שותפים</h2>
          <p className="legal-text">
            Chiller Travel משתתפת בתוכניות שיווק שותפים. משמעות הדבר היא שאנו מטמיעים קישורי הפניה ייעודיים לספקי נסיעות, לינה, טיסות וסיורים של צד שלישי. כאשר משתמשים לוחצים על קישורים אלה ומבצעים רכישה או הזמנה, Chiller Travel מקבלת עמלת הפניה מהספק הרלוונטי. עסקאות אלו מתבצעות ללא כל עלות נוספת מצד המשתמש, ומערכות היחסים שלנו עם השותפים אינן משפיעות על המחיר שאתם משלמים.
          </p>
        </section>

        <section className="legal-section">
          <h2 style={{ fontSize: '1.4rem', color: '#38bdf8' }}>3. תמחור דינמי וזמינות</h2>
          <p className="legal-text">
            כל התעריפים, העמלות, לוחות הזמנים ופרטי זמינות ההזמנות המוצגים או המוצעים על ידי בוט הנסיעות משתנים בזמן אמת בהתאם לביקושים אצל הספקים, שינויים עונתיים ועדכוני מלאי. Chiller Travel אינה מבטיחה תמחור או זמינות של חדרים או מושבים. המחירים וההזמנות ננעלים והופכים למחייבים מבחינה משפטית רק לאחר תשלום מלא, אישור וקבלת קבלה רשמית בפלטפורמה של ספק הקצה (הצד השלישי).
          </p>
        </section>

        <section className="legal-section">
          <h2 style={{ fontSize: '1.4rem', color: '#38bdf8' }}>4. ספורט, בטיחות וביטוח מטיילים</h2>
          <p className="legal-text">
            המלצות הנסיעה ומסלולי הטיול המסופקים על ידי סוכן הבינה המלאכותית שלנו מיועדים להשראה והכוונה כללית בלבד. הם אינם מהווים ייעוץ מקצועי, משפטי, רפואי או ייעוץ בטיחות רשמי. טיולי תרמילאים ופעילויות אקסטרים כרוכים בסכנות אינהרנטיות. המשתמשים אחראים באופן בלעדי ומלא לרכישת ביטוח נסיעות מקיף הכולל כיסוי לפעילויות בסיכון גבוה, ספורט אתגרי וטרקים בגבהים, כמו גם לקבלת ייעוץ רפואי מקצועי (כולל חיסונים נדרשים) והערכת תנאי הבטיחות, מזג האוויר והתנאים הפיזיים ביעדים. Chiller Travel אינה נושאת בכל אחריות לפציעות, מחלות, תאונות, נזק לרכוש או הפסדים כספיים שייגרמו במהלך הטיול.
          </p>
        </section>

        <section className="legal-section">
          <h2 style={{ fontSize: '1.4rem', color: '#38bdf8' }}>5. אשרות, דרכונים ומעברי גבול</h2>
          <p className="legal-text">
            מעבר גבולות בינלאומיים, גישה לאזורים מרוחקים או כניסה למדינות זרות דורשים תיעוד משפטי קפדני. אתם אחראים באופן בלעדי ומלא לוודא את תוקף הדרכון שלכם, להנפיק אשרות כניסה (ויזות) נדרשות, אישורים או כרטיסי תייר, ולבדוק את תקנות מעבר הגבול היבשתי, הימי או האווירי עבור כל מסלול המוצע על ידי הבוט שלנו. Chiller Travel אינה אחראית לסירובי כניסה, עיכובים או ביטולי נסיעות הנובעים מבעיות באשרות או במסמכים.
          </p>
        </section>

        <section className="legal-section">
          <h2 style={{ fontSize: '1.4rem', color: '#38bdf8' }}>6. ביטולים וחוקי הגנת הצרכן</h2>
          <p className="legal-text">
            Chiller Travel פועלת אך ורק כפלטפורמת הפניה של שותפים. איננו סוכנות נסיעות, מפעיל טיולים או ספק הזמנות ישיר (Merchant of Record). איננו גובים תשלומים, מנפיקים כרטיסים או מטפלים בשינויי הזמנות. כפועל יוצא מכך, כל הביטולים, בקשות ההחזר, שינויי לוחות הזמנים או בעיות שירות הלקוחות כפופים אך ורק לתנאים, למדיניות הביטולים ולחוקי הגנת הצרכן המקומיים (כולל חוק הגנת הצרכן הישראלי, ככל שהוא חל על פי דין) של ספק הקצה או ספק השירות השלישי. כל תביעה משפטית, מחלוקת או תלונה יש להגיש ישירות נגד ספק הקצה, ולא נגד Chiller Travel.
          </p>
        </section>

        <section className="legal-section">
          <h2 style={{ fontSize: '1.4rem', color: '#38bdf8' }}>7. קניין רוחני והתנהגות משתמשים</h2>
          <p className="legal-text">
            כל הטקסטים, הגרפיקה, עיצובי ממשק המשתמש, הלוגואים, התוכנה והפלטים המופקים על ידי הבינה המלאכותית (כולל מסלולי טיול מותאמים אישית) המוצגים ב-Chiller Travel מוגנים על ידי חוקי קניין רוחני. חל איסור מוחלט על המשתמשים לגרד מידע (scraping), להעתיק, לשכפל, להנדס לאחור, למסחר, למכור מחדש או לפרסם מחדש את המסלולים המופקים על ידי ה-AI, נתוני האתר, תכני מסד הנתונים או פלטי הבוט לכל מטרה מסחרית או ציבורית ללא קבלת אישור מראש ובכתב.
          </p>
        </section>

        <section className="legal-section">
          <h2 style={{ fontSize: '1.4rem', color: '#38bdf8' }}>8. יצירת קשר</h2>
          <div className="legal-highlight-box" style={{ borderLeft: 'none', borderRight: '4px solid #38bdf8', borderRadius: '12px 0 0 12px' }}>
            <p>
              לכל פנייה, שלחו הודעה עם שמכם המלא ל-<a href="mailto:chillerbot1405@gmail.com" className="legal-link">chillerbot1405@gmail.com</a>.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}

export default TermsOfService;
